import {
  resolveRevenueAnalyticsPeriod,
  summarizeCustomerConcentration,
  summarizeCustomerRevenue,
  summarizeRevenueByDimension,
} from '@/lib/financial-data/reporting/revenue-analytics-calculations'
import type { FinancialRevenueDimensionType } from '@/types/database'
import type { GenUiWidget, GenUiWidgetType } from '@/lib/gen-ui/types'
import { widgetId } from '../shared'
import type { GenUiDataContext, PlannerWidget } from '../types'

function title(spec: PlannerWidget, fallback: string) {
  return spec.title ?? fallback
}

function reason(spec: PlannerWidget, fallback: string) {
  return spec.reason ?? fallback
}

function currentDate() {
  return new Date().toISOString().slice(0, 10)
}

function unavailable<T extends GenUiWidget>(widget: T, message: string): T {
  return { ...widget, state: { status: 'unavailable', message } }
}

function partial<T extends GenUiWidget>(widget: T, message: string): T {
  return { ...widget, state: { status: 'partial', message } }
}

export function revenueDimensionTypeForMessage(message: string): FinancialRevenueDimensionType {
  if (/\bsubscriptions?\b/i.test(message)) return 'subscription'
  if (/\bdepartments?\b/i.test(message)) return 'department'
  if (/\bbusiness units?\b|\bdivisions?\b/i.test(message)) return 'business_unit'
  if (/\btracking (?:category|categories|option|options)\b/i.test(message)) return 'tracking'
  return 'product_service'
}

export function buildCustomerRevenueBreakdownWidget(
  spec: PlannerWidget,
  index: number,
  context: GenUiDataContext,
): GenUiWidget {
  const period = resolveRevenueAnalyticsPeriod(context.userMessage, currentDate())
  const groups = summarizeCustomerRevenue(context.stage3Data, period)
  const widget: GenUiWidget = {
    id: widgetId('customer_revenue_breakdown', index),
    type: 'customer_revenue_breakdown',
    title: title(spec, 'Customer revenue breakdown'),
    reason: reason(spec, 'This ranks customers by recorded revenue for the selected period.'),
    data: {
      groups,
      note: 'Customers are ranked by net recorded revenue. Sources and currencies remain separate.',
    },
  }
  if (!context.stage3Data.capabilities.includes('customer_revenue')) {
    return unavailable(widget, 'Customer-linked revenue entries are required for this breakdown.')
  }
  return groups.some((group) => group.unallocatedRevenue !== 0)
    ? partial(widget, 'Some recorded revenue has no mapped customer and is shown as unallocated.')
    : widget
}

export function buildCustomerConcentrationRiskWidget(
  spec: PlannerWidget,
  index: number,
  context: GenUiDataContext,
): GenUiWidget {
  const period = resolveRevenueAnalyticsPeriod(context.userMessage, currentDate())
  const groups = summarizeCustomerConcentration(context.stage3Data, period)
  const widget: GenUiWidget = {
    id: widgetId('customer_concentration_risk', index),
    type: 'customer_concentration_risk',
    title: title(spec, 'Customer concentration risk'),
    reason: reason(spec, 'This measures the revenue share generated by the largest recorded customers.'),
    data: {
      groups,
      note: 'Shares use total recorded revenue, including unallocated revenue, so missing customer mappings do not inflate concentration.',
    },
  }
  if (!context.stage3Data.capabilities.includes('customer_revenue')) {
    return unavailable(widget, 'Customer-linked revenue entries are required for concentration analysis.')
  }
  return groups.some((group) => group.status === 'partial_unallocated')
    ? partial(widget, 'Customer concentration is a lower-bound estimate because some revenue is unallocated.')
    : widget
}

export function buildProductServiceRevenueWidget(
  spec: PlannerWidget,
  index: number,
  context: GenUiDataContext,
): GenUiWidget {
  const period = resolveRevenueAnalyticsPeriod(context.userMessage, currentDate())
  const dimensionType = revenueDimensionTypeForMessage(context.userMessage)
  const groups = summarizeRevenueByDimension({ data: context.stage3Data, period, dimensionType })
  const label = {
    product_service: 'Product or service revenue',
    subscription: 'Subscription revenue',
    department: 'Revenue by department',
    business_unit: 'Revenue by business unit',
    tracking: 'Revenue by tracking category',
  }[dimensionType]
  const widget: GenUiWidget = {
    id: widgetId('product_service_revenue', index),
    type: 'product_service_revenue',
    title: title(spec, label),
    reason: reason(spec, 'This ranks recorded revenue using explicitly stored dimensional classifications.'),
    data: {
      dimensionType,
      groups,
      note: groups.length > 0
        ? 'Each dimension group is an independent revenue axis; sources and currencies remain separate.'
        : `No ${label.toLowerCase()} classifications are recorded for this period.`,
    },
  }
  if (!context.stage3Data.capabilities.includes('revenue_dimensions')) {
    return unavailable(widget, 'Revenue entries with stored dimensional classifications are required.')
  }
  const hasRevenueInPeriod = context.stage3Data.revenueEntries.some((entry) =>
    entry.status === 'posted' && entry.revenue_date >= period.periodStart && entry.revenue_date <= period.periodEnd
  )
  if (groups.length === 0 && hasRevenueInPeriod) {
    return unavailable(widget, `No ${label.toLowerCase()} classifications are recorded for this period.`)
  }
  return groups.some((group) => group.unallocatedRevenue !== 0)
    ? partial(widget, 'Some recorded revenue has no value for the selected dimension and is shown as unallocated.')
    : widget
}

export const STAGE6_WIDGET_TYPES: GenUiWidgetType[] = [
  'customer_revenue_breakdown',
  'customer_concentration_risk',
  'product_service_revenue',
]
