import type { GenUiWidgetType } from '@/lib/gen-ui/types'
import type {
  GenUiDataRequirements,
  GenUiSupportedFilter,
  GenUiSupportedPeriod,
  GenUiWidgetCategory,
} from '@/lib/gen-ui/requirements'

export const GEN_UI_WIDGET_SIZES = ['1x1', '1x2', '2x2'] as const

export type GenUiWidgetSize = (typeof GEN_UI_WIDGET_SIZES)[number]

// Size names use rows x columns. The canvas has two columns at desktop widths.
export const GEN_UI_WIDGET_SIZE_DIMENSIONS = {
  '1x1': { rowSpan: 1, columnSpan: 1 },
  '1x2': { rowSpan: 1, columnSpan: 2 },
  '2x2': { rowSpan: 2, columnSpan: 2 },
} as const satisfies Record<
  GenUiWidgetSize,
  { rowSpan: 1 | 2; columnSpan: 1 | 2 }
>

export interface GenUiWidgetCatalogEntry {
  type: GenUiWidgetType
  label: string
  description: string
  selectionGuidance: string
  defaultSize: GenUiWidgetSize
  category: GenUiWidgetCategory
  defaultColumnSpan: 1 | 2
  dataRequirements: GenUiDataRequirements
  supportedPeriods: readonly GenUiSupportedPeriod[]
  supportedFilters: readonly GenUiSupportedFilter[]
  requiresForecast: boolean
  requiresDimensionalData: boolean
}

export const GEN_UI_WIDGET_CATALOG = {
  metric_snapshot: {
    type: 'metric_snapshot',
    label: 'Metric snapshot',
    description: 'A focused set of live financial metrics and their sources.',
    selectionGuidance: 'Select only the metric keys directly relevant to the question.',
    defaultSize: '1x1',
    category: 'overview',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  data_connections: {
    type: 'data_connections',
    label: 'Document sources',
    description: 'Supported uploaded financial files and review availability.',
    selectionGuidance: 'Select for document, file upload, or source-review questions.',
    defaultSize: '1x2',
    category: 'connections',
    defaultColumnSpan: 2,
    dataRequirements: { required: [], optional: ['document_sources'] },
    supportedPeriods: [],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  metric_trend_chart: {
    type: 'metric_trend_chart',
    label: 'Historical metric trend',
    description: 'Shows deterministic historical movement for one financial metric.',
    selectionGuidance: 'Select only for a historical question that names one metric such as cash, revenue, expenses, burn rate, or runway.',
    defaultSize: '2x2',
    category: 'trends',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['three_months', 'six_months', 'all_history'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  metric_forecast_chart: {
    type: 'metric_forecast_chart',
    label: 'Metric forecast',
    description: 'Shows deterministic actual and projected movement for one financial metric.',
    selectionGuidance: 'Select only for a future-focused question that names cash, revenue, expenses, burn rate, or runway.',
    defaultSize: '2x2',
    category: 'forecasting',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_forecast'], optional: ['metric_history'] },
    supportedPeriods: ['three_months', 'six_months'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: true,
    requiresDimensionalData: false,
  },
  scenario_comparison: {
    type: 'scenario_comparison',
    label: 'Scenario comparison',
    description: 'Compares the current runway with modeled burn changes.',
    selectionGuidance: 'Select for what-if, hiring, saving, or cost-change questions.',
    defaultSize: '2x2',
    category: 'scenarios',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['scenario_result'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: ['scenario'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  scenario_analysis: {
    type: 'scenario_analysis',
    label: 'Scenario analysis',
    description: 'Shows the exact deterministic current-run-rate and historical-trend scenario result.',
    selectionGuidance: 'Use only when the model_scenario tool returned a ready structured result.',
    defaultSize: '2x2',
    category: 'scenarios',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['scenario_result'], optional: ['metric_history'] },
    supportedPeriods: ['three_months', 'six_months'],
    supportedFilters: ['scenario', 'source'],
    requiresForecast: true,
    requiresDimensionalData: false,
  },
  planning_checklist: {
    type: 'planning_checklist',
    label: 'Planning checklist',
    description: 'Prioritized actions based on current runway conditions.',
    selectionGuidance: 'Select when the user needs concrete next steps.',
    defaultSize: '1x1',
    category: 'planning',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics', 'runway_trend'] },
    supportedPeriods: ['current'],
    supportedFilters: [],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  risk_threshold_timeline: {
    type: 'risk_threshold_timeline',
    label: 'Risk threshold timing',
    description: 'Shows current runway risk and time to caution or urgent thresholds.',
    selectionGuidance: 'Select for runway risk, timing, or buffer questions.',
    defaultSize: '1x1',
    category: 'risk',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics', 'runway_trend'] },
    supportedPeriods: ['current'],
    supportedFilters: [],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  metric_source_evidence: {
    type: 'metric_source_evidence',
    label: 'Metric source evidence',
    description: 'Displays the values and provenance supporting the answer.',
    selectionGuidance: 'Select for source, evidence, uploaded-data, or metric questions.',
    defaultSize: '1x2',
    category: 'evidence',
    defaultColumnSpan: 2,
    dataRequirements: { required: [], optional: ['aggregate_metrics', 'document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  missing_data_panel: {
    type: 'missing_data_panel',
    label: 'Missing data',
    description: 'Explains which required financial inputs are unavailable.',
    selectionGuidance: 'Select when missing inputs materially limit the answer.',
    defaultSize: '1x1',
    category: 'data_quality',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: ['metric'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  highlight_explainer: {
    type: 'highlight_explainer',
    label: 'Highlighted insight',
    description: 'Connects selected workspace text to a focused follow-up question.',
    selectionGuidance: 'Select when the request originated from highlighted workspace text.',
    defaultSize: '1x2',
    category: 'explanation',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['selection_context'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: [],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  cash_balance: {
    type: 'cash_balance',
    label: 'Cash balance',
    description: 'Current available cash from the latest trusted aggregate observation.',
    selectionGuidance: 'Use for direct questions about current cash, cash on hand, or available cash.',
    defaultSize: '1x1',
    category: 'cash',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  revenue_snapshot: {
    type: 'revenue_snapshot',
    label: 'Revenue snapshot',
    description: 'Latest trusted monthly revenue observation with reporting-period context.',
    selectionGuidance: 'Use for direct questions about current or latest revenue.',
    defaultSize: '1x1',
    category: 'revenue',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current', 'month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  revenue_trend: {
    type: 'revenue_trend',
    label: 'Revenue trend',
    description: 'Historical monthly revenue using distinct reporting periods.',
    selectionGuidance: 'Use when the user asks how revenue changed over time.',
    defaultSize: '2x2',
    category: 'revenue',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['three_months', 'six_months', 'all_history'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  revenue_growth: {
    type: 'revenue_growth',
    label: 'Revenue growth',
    description: 'Growth between the latest two distinct revenue reporting periods.',
    selectionGuidance: 'Use for month-on-month revenue growth questions.',
    defaultSize: '1x1',
    category: 'revenue',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  expense_summary: {
    type: 'expense_summary',
    label: 'Expense summary',
    description: 'Latest trusted monthly expense total with reporting-period context.',
    selectionGuidance: 'Use for direct questions about current or latest total spending.',
    defaultSize: '1x1',
    category: 'expenses',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current', 'month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  expense_trend: {
    type: 'expense_trend',
    label: 'Expense trend',
    description: 'Historical monthly expenses using distinct reporting periods.',
    selectionGuidance: 'Use when the user asks how expenses or spending changed over time.',
    defaultSize: '2x2',
    category: 'expenses',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['three_months', 'six_months', 'all_history'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  accounts_receivable: {
    type: 'accounts_receivable',
    label: 'Accounts receivable',
    description: 'Current aggregate amount owed by customers.',
    selectionGuidance: 'Use for current receivables or customer money owed questions without invoice detail.',
    defaultSize: '1x1',
    category: 'receivables',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  accounts_payable: {
    type: 'accounts_payable',
    label: 'Accounts payable',
    description: 'Current aggregate amount owed to suppliers and creditors.',
    selectionGuidance: 'Use for current payables or supplier money owed questions without bill detail.',
    defaultSize: '1x1',
    category: 'payables',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  ai_financial_brief: {
    type: 'ai_financial_brief',
    label: 'AI financial brief',
    description: 'A concise deterministic brief assembled from verified structured financial facts.',
    selectionGuidance: 'Use for financial overview, health-check, risk, or opportunity summary questions.',
    defaultSize: '1x2',
    category: 'brief',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['metric_history', 'runway_trend'] },
    supportedPeriods: ['current', 'month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
} as const satisfies Record<GenUiWidgetType, GenUiWidgetCatalogEntry>

export const GEN_UI_WIDGET_CATALOG_ENTRIES = Object.values(
  GEN_UI_WIDGET_CATALOG,
)

export function describeGenUiWidgetCatalog() {
  return GEN_UI_WIDGET_CATALOG_ENTRIES.map(
    ({ type, selectionGuidance }) => `${type}: ${selectionGuidance}`,
  ).join('\n')
}
