import type { GenUiWidgetType } from '@/lib/gen-ui/types'
import type {
  GenUiDataRequirements,
  GenUiSupportedFilter,
  GenUiSupportedPeriod,
  GenUiWidgetCategory,
} from '@/lib/gen-ui/requirements'

export const GEN_UI_WIDGET_SIZES = ['1x1', '1x2', '2x2'] as const

export type GenUiWidgetSize = (typeof GEN_UI_WIDGET_SIZES)[number]

// Size names use rows x columns. The canvas has two columns at desktop widths.
export const GEN_UI_WIDGET_SIZE_DIMENSIONS = {
  '1x1': { rowSpan: 1, columnSpan: 1 },
  '1x2': { rowSpan: 1, columnSpan: 2 },
  '2x2': { rowSpan: 2, columnSpan: 2 },
} as const satisfies Record<
  GenUiWidgetSize,
  { rowSpan: 1 | 2; columnSpan: 1 | 2 }
>

export interface GenUiWidgetCatalogEntry {
  type: GenUiWidgetType
  label: string
  description: string
  selectionGuidance: string
  defaultSize: GenUiWidgetSize
  category: GenUiWidgetCategory
  defaultColumnSpan: 1 | 2
  dataRequirements: GenUiDataRequirements
  supportedPeriods: readonly GenUiSupportedPeriod[]
  supportedFilters: readonly GenUiSupportedFilter[]
  requiresForecast: boolean
  requiresDimensionalData: boolean
}

export const GEN_UI_WIDGET_CATALOG = {
  metric_snapshot: {
    type: 'metric_snapshot',
    label: 'Metric snapshot',
    description: 'A focused set of live financial metrics and their sources.',
    selectionGuidance: 'Select only the metric keys directly relevant to the question.',
    defaultSize: '1x1',
    category: 'overview',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  data_connections: {
    type: 'data_connections',
    label: 'Document sources',
    description: 'Supported uploaded financial files and review availability.',
    selectionGuidance: 'Select for document, file upload, or source-review questions.',
    defaultSize: '1x2',
    category: 'connections',
    defaultColumnSpan: 2,
    dataRequirements: { required: [], optional: ['document_sources'] },
    supportedPeriods: [],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  metric_trend_chart: {
    type: 'metric_trend_chart',
    label: 'Historical metric trend',
    description: 'Shows deterministic historical movement for one financial metric.',
    selectionGuidance: 'Select only for a historical question that names one metric such as cash, revenue, expenses, burn rate, or runway.',
    defaultSize: '2x2',
    category: 'trends',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['three_months', 'six_months', 'all_history'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  metric_forecast_chart: {
    type: 'metric_forecast_chart',
    label: 'Metric forecast',
    description: 'Shows deterministic actual and projected movement for one financial metric.',
    selectionGuidance: 'Select only for a future-focused question that names cash, revenue, expenses, burn rate, or runway.',
    defaultSize: '2x2',
    category: 'forecasting',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_forecast'], optional: ['metric_history'] },
    supportedPeriods: ['three_months', 'six_months'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: true,
    requiresDimensionalData: false,
  },
  scenario_comparison: {
    type: 'scenario_comparison',
    label: 'Scenario comparison',
    description: 'Compares the current runway with modeled burn changes.',
    selectionGuidance: 'Select for what-if, hiring, saving, or cost-change questions.',
    defaultSize: '2x2',
    category: 'scenarios',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['scenario_result'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: ['scenario'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  scenario_analysis: {
    type: 'scenario_analysis',
    label: 'Scenario analysis',
    description: 'Shows the exact deterministic current-run-rate and historical-trend scenario result.',
    selectionGuidance: 'Use only when the model_scenario tool returned a ready structured result.',
    defaultSize: '2x2',
    category: 'scenarios',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['scenario_result'], optional: ['metric_history'] },
    supportedPeriods: ['three_months', 'six_months'],
    supportedFilters: ['scenario', 'source'],
    requiresForecast: true,
    requiresDimensionalData: false,
  },
  planning_checklist: {
    type: 'planning_checklist',
    label: 'Planning checklist',
    description: 'Prioritized actions based on current runway conditions.',
    selectionGuidance: 'Select when the user needs concrete next steps.',
    defaultSize: '1x1',
    category: 'planning',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics', 'runway_trend'] },
    supportedPeriods: ['current'],
    supportedFilters: [],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  risk_threshold_timeline: {
    type: 'risk_threshold_timeline',
    label: 'Risk threshold timing',
    description: 'Shows current runway risk and time to caution or urgent thresholds.',
    selectionGuidance: 'Select for runway risk, timing, or buffer questions.',
    defaultSize: '1x1',
    category: 'risk',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics', 'runway_trend'] },
    supportedPeriods: ['current'],
    supportedFilters: [],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  metric_source_evidence: {
    type: 'metric_source_evidence',
    label: 'Metric source evidence',
    description: 'Displays the values and provenance supporting the answer.',
    selectionGuidance: 'Select for source, evidence, uploaded-data, or metric questions.',
    defaultSize: '1x2',
    category: 'evidence',
    defaultColumnSpan: 2,
    dataRequirements: { required: [], optional: ['aggregate_metrics', 'document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['metric', 'source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  missing_data_panel: {
    type: 'missing_data_panel',
    label: 'Missing data',
    description: 'Explains which required financial inputs are unavailable.',
    selectionGuidance: 'Select when missing inputs materially limit the answer.',
    defaultSize: '1x1',
    category: 'data_quality',
    defaultColumnSpan: 1,
    dataRequirements: { required: [], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: ['metric'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  highlight_explainer: {
    type: 'highlight_explainer',
    label: 'Highlighted insight',
    description: 'Connects selected workspace text to a focused follow-up question.',
    selectionGuidance: 'Select when the request originated from highlighted workspace text.',
    defaultSize: '1x2',
    category: 'explanation',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['selection_context'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['current'],
    supportedFilters: [],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  cash_balance: {
    type: 'cash_balance',
    label: 'Cash balance',
    description: 'Current available cash from the latest trusted aggregate observation.',
    selectionGuidance: 'Use for direct questions about current cash, cash on hand, or available cash.',
    defaultSize: '1x1',
    category: 'cash',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  revenue_snapshot: {
    type: 'revenue_snapshot',
    label: 'Revenue snapshot',
    description: 'Latest trusted monthly revenue observation with reporting-period context.',
    selectionGuidance: 'Use for direct questions about current or latest revenue.',
    defaultSize: '1x1',
    category: 'revenue',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current', 'month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  revenue_trend: {
    type: 'revenue_trend',
    label: 'Revenue trend',
    description: 'Historical monthly revenue using distinct reporting periods.',
    selectionGuidance: 'Use when the user asks how revenue changed over time.',
    defaultSize: '2x2',
    category: 'revenue',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['three_months', 'six_months', 'all_history'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  revenue_growth: {
    type: 'revenue_growth',
    label: 'Revenue growth',
    description: 'Growth between the latest two distinct revenue reporting periods.',
    selectionGuidance: 'Use for month-on-month revenue growth questions.',
    defaultSize: '1x1',
    category: 'revenue',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  expense_summary: {
    type: 'expense_summary',
    label: 'Expense summary',
    description: 'Latest trusted monthly expense total with reporting-period context.',
    selectionGuidance: 'Use for direct questions about current or latest total spending.',
    defaultSize: '1x1',
    category: 'expenses',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current', 'month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  expense_trend: {
    type: 'expense_trend',
    label: 'Expense trend',
    description: 'Historical monthly expenses using distinct reporting periods.',
    selectionGuidance: 'Use when the user asks how expenses or spending changed over time.',
    defaultSize: '2x2',
    category: 'expenses',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_history'], optional: ['aggregate_metrics'] },
    supportedPeriods: ['three_months', 'six_months', 'all_history'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  accounts_receivable: {
    type: 'accounts_receivable',
    label: 'Accounts receivable',
    description: 'Current aggregate amount owed by customers.',
    selectionGuidance: 'Use for current receivables or customer money owed questions without invoice detail.',
    defaultSize: '1x1',
    category: 'receivables',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  accounts_payable: {
    type: 'accounts_payable',
    label: 'Accounts payable',
    description: 'Current aggregate amount owed to suppliers and creditors.',
    selectionGuidance: 'Use for current payables or supplier money owed questions without bill detail.',
    defaultSize: '1x1',
    category: 'payables',
    defaultColumnSpan: 1,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['document_sources'] },
    supportedPeriods: ['current'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  ai_financial_brief: {
    type: 'ai_financial_brief',
    label: 'AI financial brief',
    description: 'A concise deterministic brief assembled from verified structured financial facts.',
    selectionGuidance: 'Use for financial overview, health-check, risk, or opportunity summary questions.',
    defaultSize: '1x2',
    category: 'brief',
    defaultColumnSpan: 2,
    dataRequirements: { required: ['aggregate_metrics'], optional: ['metric_history', 'runway_trend'] },
    supportedPeriods: ['current', 'month'],
    supportedFilters: ['source'],
    requiresForecast: false,
    requiresDimensionalData: false,
  },
  cash_flow_summary: {
    type: 'cash_flow_summary', label: 'Cash flow summary',
    description: 'Recorded cash inflows, outflows, and net cash movement for a reporting period.',
    selectionGuidance: 'Use for questions about actual money in, money out, or net cash movement.',
    defaultSize: '1x2', category: 'cash', defaultColumnSpan: 2,
    dataRequirements: { required: ['cash_flow_history'], optional: ['financial_statements'] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['source'],
    requiresForecast: false, requiresDimensionalData: false,
  },
  cash_flow_forecast: {
    type: 'cash_flow_forecast', label: 'Cash flow forecast',
    description: 'Projected cash balance from actual cash movements and the latest cash balance.',
    selectionGuidance: 'Use for 30, 60, or 90 day future cash-balance questions.',
    defaultSize: '2x2', category: 'cash', defaultColumnSpan: 2,
    dataRequirements: { required: ['cash_flow_history', 'aggregate_metrics'], optional: [] },
    supportedPeriods: ['thirty_days', 'sixty_days', 'ninety_days'], supportedFilters: ['source'],
    requiresForecast: true, requiresDimensionalData: false,
  },
  revenue_forecast: {
    type: 'revenue_forecast', label: 'Revenue forecast',
    description: 'Expected revenue from the recorded date-aware revenue trend.',
    selectionGuidance: 'Use for future revenue questions over the next few months.',
    defaultSize: '2x2', category: 'revenue', defaultColumnSpan: 2,
    dataRequirements: { required: ['metric_forecast'], optional: ['metric_history'] },
    supportedPeriods: ['three_months', 'six_months', 'twelve_months'], supportedFilters: ['source'],
    requiresForecast: true, requiresDimensionalData: false,
  },
  profit_snapshot: {
    type: 'profit_snapshot', label: 'Profit snapshot',
    description: 'Gross, operating, and net profit from the latest profit-and-loss period.',
    selectionGuidance: 'Use for current profit questions and always identify available profit types.',
    defaultSize: '1x2', category: 'profit', defaultColumnSpan: 2,
    dataRequirements: { required: ['financial_statements'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['profit_type', 'source'],
    requiresForecast: false, requiresDimensionalData: false,
  },
  profit_trend: {
    type: 'profit_trend', label: 'Profit trend',
    description: 'Historical gross, operating, or net profit across reporting periods.',
    selectionGuidance: 'Use for historical profit movement and identify the profit type.',
    defaultSize: '2x2', category: 'profit', defaultColumnSpan: 2,
    dataRequirements: { required: ['financial_statements'], optional: [] },
    supportedPeriods: ['three_months', 'six_months', 'all_history'], supportedFilters: ['profit_type', 'source'],
    requiresForecast: false, requiresDimensionalData: false,
  },
  profit_forecast: {
    type: 'profit_forecast', label: 'Profit forecast',
    description: 'Expected gross, operating, or net profit from recorded profit history.',
    selectionGuidance: 'Use for future profit questions and show the forecast method.',
    defaultSize: '2x2', category: 'profit', defaultColumnSpan: 2,
    dataRequirements: { required: ['financial_statements'], optional: [] },
    supportedPeriods: ['three_months', 'six_months', 'twelve_months'], supportedFilters: ['profit_type', 'source'],
    requiresForecast: true, requiresDimensionalData: false,
  },
  profit_margin: {
    type: 'profit_margin', label: 'Profit margin',
    description: 'Gross, operating, or net profit as a percentage of revenue.',
    selectionGuidance: 'Use for margin questions and always identify which margin is shown.',
    defaultSize: '1x1', category: 'profit', defaultColumnSpan: 1,
    dataRequirements: { required: ['financial_statements'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['profit_type', 'source'],
    requiresForecast: false, requiresDimensionalData: false,
  },
  break_even_analysis: {
    type: 'break_even_analysis', label: 'Break-even analysis',
    description: 'Revenue required to cover explicitly classified fixed and variable costs.',
    selectionGuidance: 'Use only when fixed and variable cost classifications are complete.',
    defaultSize: '1x2', category: 'profit', defaultColumnSpan: 2,
    dataRequirements: { required: ['financial_statements', 'cost_classification'], optional: [] },
    supportedPeriods: ['month'], supportedFilters: ['source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  break_even_progress: {
    type: 'break_even_progress', label: 'Break-even progress',
    description: 'Current revenue progress toward the calculated monthly break-even point.',
    selectionGuidance: 'Use for progress-to-break-even questions after a valid break-even calculation.',
    defaultSize: '1x1', category: 'profit', defaultColumnSpan: 1,
    dataRequirements: { required: ['financial_statements', 'cost_classification'], optional: [] },
    supportedPeriods: ['month'], supportedFilters: ['source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  expense_breakdown: {
    type: 'expense_breakdown', label: 'Expense breakdown',
    description: 'Expense totals divided into canonical categories.',
    selectionGuidance: 'Use when the user asks where money is being spent.',
    defaultSize: '2x2', category: 'expenses', defaultColumnSpan: 2,
    dataRequirements: { required: ['expense_categories'], optional: ['financial_statements'] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['category', 'source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  largest_expenses: {
    type: 'largest_expenses', label: 'Largest expenses',
    description: 'Highest posted cash outflow transactions for the selected period.',
    selectionGuidance: 'Use for largest cost, payment, purchase, or supplier-spend questions.',
    defaultSize: '1x2', category: 'expenses', defaultColumnSpan: 2,
    dataRequirements: { required: ['expense_transactions'], optional: ['expense_categories'] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['category', 'source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  expense_change_detector: {
    type: 'expense_change_detector', label: 'Expense change detector',
    description: 'Categories with the largest change between distinct reporting periods.',
    selectionGuidance: 'Use for significant spending-change or cost-increase questions.',
    defaultSize: '1x2', category: 'expenses', defaultColumnSpan: 2,
    dataRequirements: { required: ['expense_categories', 'financial_statements'], optional: [] },
    supportedPeriods: ['month', 'quarter'], supportedFilters: ['category', 'source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  budget_vs_actual: {
    type: 'budget_vs_actual', label: 'Budget vs actual',
    description: 'Actual performance compared with aligned budget lines.',
    selectionGuidance: 'Use for plan-versus-actual questions when a budget is available.',
    defaultSize: '2x2', category: 'budgets', defaultColumnSpan: 2,
    dataRequirements: { required: ['budget_lines', 'financial_statements'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['budget', 'category'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  budget_remaining: {
    type: 'budget_remaining', label: 'Budget remaining',
    description: 'Amount remaining within the selected budget.',
    selectionGuidance: 'Use for remaining-spend or remaining-budget questions.',
    defaultSize: '1x1', category: 'budgets', defaultColumnSpan: 1,
    dataRequirements: { required: ['budget_lines', 'financial_statements'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['budget', 'category'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  budget_forecast: {
    type: 'budget_forecast', label: 'Budget forecast',
    description: 'Projected budget outcome using actual run rate and elapsed time.',
    selectionGuidance: 'Use when the user asks whether a budget will finish above or below plan.',
    defaultSize: '1x2', category: 'budgets', defaultColumnSpan: 2,
    dataRequirements: { required: ['budget_lines', 'financial_statements'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year'], supportedFilters: ['budget', 'category'],
    requiresForecast: true, requiresDimensionalData: true,
  },
  cash_inflow_forecast: {
    type: 'cash_inflow_forecast', label: 'Cash inflow forecast',
    description: 'Expected incoming cash based on recorded cash inflow periods.',
    selectionGuidance: 'Use for future incoming-cash questions without implying invoice due dates.',
    defaultSize: '2x2', category: 'cash', defaultColumnSpan: 2,
    dataRequirements: { required: ['cash_flow_history'], optional: [] },
    supportedPeriods: ['three_months', 'six_months'], supportedFilters: ['source'],
    requiresForecast: true, requiresDimensionalData: false,
  },
  cash_outflow_forecast: {
    type: 'cash_outflow_forecast', label: 'Cash outflow forecast',
    description: 'Expected outgoing cash based on recorded cash outflow periods.',
    selectionGuidance: 'Use for future outgoing-cash questions without implying bill due dates.',
    defaultSize: '2x2', category: 'cash', defaultColumnSpan: 2,
    dataRequirements: { required: ['cash_flow_history'], optional: [] },
    supportedPeriods: ['three_months', 'six_months'], supportedFilters: ['source'],
    requiresForecast: true, requiresDimensionalData: false,
  },
  overdue_invoices: {
    type: 'overdue_invoices', label: 'Overdue invoices',
    description: 'Open customer invoices past their stored due date, grouped by source and currency.',
    selectionGuidance: 'Use for overdue customer invoice counts, balances, or collection-priority questions.',
    defaultSize: '1x2', category: 'invoices', defaultColumnSpan: 2,
    dataRequirements: { required: ['invoice_details'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source', 'counterparty', 'invoice_status'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  invoice_ageing: {
    type: 'invoice_ageing', label: 'Invoice ageing',
    description: 'Overdue customer balances grouped into due-date ageing buckets.',
    selectionGuidance: 'Use for invoice ageing or aged-receivables questions; age from the stored due date.',
    defaultSize: '2x2', category: 'invoices', defaultColumnSpan: 2,
    dataRequirements: { required: ['invoice_details'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source', 'counterparty'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  expected_payments: {
    type: 'expected_payments', label: 'Expected payments',
    description: 'Open customer invoice balances due during the next 7, 14, or 30 days.',
    selectionGuidance: 'Use for expected customer receipts and clearly state that invoice due dates are not payment guarantees.',
    defaultSize: '1x2', category: 'invoices', defaultColumnSpan: 2,
    dataRequirements: { required: ['invoice_details'], optional: [] },
    supportedPeriods: ['seven_days', 'fourteen_days', 'thirty_days'], supportedFilters: ['source', 'counterparty'],
    requiresForecast: true, requiresDimensionalData: true,
  },
  bills_due: {
    type: 'bills_due', label: 'Bills due',
    description: 'Open supplier bills due during the next 7, 14, or 30 days.',
    selectionGuidance: 'Use for upcoming supplier-payment and near-term payable questions.',
    defaultSize: '1x2', category: 'payables', defaultColumnSpan: 2,
    dataRequirements: { required: ['bill_details'], optional: [] },
    supportedPeriods: ['seven_days', 'fourteen_days', 'thirty_days'], supportedFilters: ['source', 'counterparty'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  working_capital: {
    type: 'working_capital', label: 'Working capital',
    description: 'Classified current assets less classified current liabilities.',
    selectionGuidance: 'Use for working-capital or short-term liquidity questions.',
    defaultSize: '1x2', category: 'balance_sheet', defaultColumnSpan: 2,
    dataRequirements: { required: ['balance_sheet'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  current_ratio: {
    type: 'current_ratio', label: 'Current ratio',
    description: 'Classified current assets divided by classified current liabilities.',
    selectionGuidance: 'Use for current-ratio questions; do not calculate with zero current liabilities.',
    defaultSize: '1x1', category: 'balance_sheet', defaultColumnSpan: 1,
    dataRequirements: { required: ['balance_sheet'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  quick_ratio: {
    type: 'quick_ratio', label: 'Quick ratio',
    description: 'Explicitly included quick assets divided by classified current liabilities.',
    selectionGuidance: 'Use for quick-ratio or acid-test questions only when all current assets have explicit treatment.',
    defaultSize: '1x1', category: 'balance_sheet', defaultColumnSpan: 1,
    dataRequirements: { required: ['balance_sheet', 'quick_ratio_classification'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  asset_summary: {
    type: 'asset_summary', label: 'Asset summary',
    description: 'Current and non-current balance-sheet assets grouped by canonical category.',
    selectionGuidance: 'Use for asset composition, balance, or breakdown questions.',
    defaultSize: '2x2', category: 'balance_sheet', defaultColumnSpan: 2,
    dataRequirements: { required: ['balance_sheet'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source', 'category'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  liability_summary: {
    type: 'liability_summary', label: 'Liability summary',
    description: 'Current and non-current balance-sheet liabilities grouped by canonical category.',
    selectionGuidance: 'Use for liability composition, balance, or breakdown questions.',
    defaultSize: '2x2', category: 'balance_sheet', defaultColumnSpan: 2,
    dataRequirements: { required: ['balance_sheet'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source', 'category'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  equity_snapshot: {
    type: 'equity_snapshot', label: 'Equity snapshot',
    description: 'Recorded equity components from the latest balance sheet.',
    selectionGuidance: 'Use for owner equity, net-assets, or equity-position questions.',
    defaultSize: '1x2', category: 'balance_sheet', defaultColumnSpan: 2,
    dataRequirements: { required: ['balance_sheet'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source', 'category'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  debt_overview: {
    type: 'debt_overview', label: 'Debt overview',
    description: 'Active recorded debt balances, rates, lenders, and maturity details.',
    selectionGuidance: 'Use for debt, loan, borrowing, or finance-facility overview questions.',
    defaultSize: '2x2', category: 'debt', defaultColumnSpan: 2,
    dataRequirements: { required: ['debt_details'], optional: [] },
    supportedPeriods: ['current'], supportedFilters: ['source', 'debt_type', 'debt_status'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  debt_repayment_timeline: {
    type: 'debt_repayment_timeline', label: 'Debt repayment timeline',
    description: 'Stored scheduled debt repayments over the next 3, 6, or 12 months.',
    selectionGuidance: 'Use for debt repayment schedules or upcoming loan-payment questions; never infer dates.',
    defaultSize: '2x2', category: 'debt', defaultColumnSpan: 2,
    dataRequirements: { required: ['debt_repayment_schedule'], optional: ['debt_details'] },
    supportedPeriods: ['three_months', 'six_months', 'twelve_months'], supportedFilters: ['source', 'debt_type'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  customer_revenue_breakdown: {
    type: 'customer_revenue_breakdown', label: 'Customer revenue breakdown',
    description: 'Recorded revenue ranked by canonical customer for a defined period.',
    selectionGuidance: 'Use when the user asks which customers generate revenue or requests top-customer revenue.',
    defaultSize: '2x2', category: 'customers', defaultColumnSpan: 2,
    dataRequirements: { required: ['customer_revenue'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year', 'three_months', 'six_months', 'twelve_months'], supportedFilters: ['source', 'customer'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  customer_concentration_risk: {
    type: 'customer_concentration_risk', label: 'Customer concentration risk',
    description: 'Top-one, top-three, and top-five shares of recorded revenue for a defined period.',
    selectionGuidance: 'Use for dependency, concentration, or revenue-risk questions about major customers.',
    defaultSize: '1x2', category: 'customers', defaultColumnSpan: 2,
    dataRequirements: { required: ['customer_revenue'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year', 'three_months', 'six_months', 'twelve_months'], supportedFilters: ['source', 'customer'],
    requiresForecast: false, requiresDimensionalData: true,
  },
  product_service_revenue: {
    type: 'product_service_revenue', label: 'Product or service revenue',
    description: 'Recorded revenue ranked by product/service or another explicitly stored revenue dimension.',
    selectionGuidance: 'Use for product, service, subscription, department, business-unit, or tracking-category revenue questions.',
    defaultSize: '2x2', category: 'revenue', defaultColumnSpan: 2,
    dataRequirements: { required: ['customer_revenue', 'revenue_dimensions'], optional: [] },
    supportedPeriods: ['month', 'quarter', 'year', 'three_months', 'six_months', 'twelve_months'], supportedFilters: ['source', 'revenue_dimension'],
    requiresForecast: false, requiresDimensionalData: true,
  },
} as const satisfies Record<GenUiWidgetType, GenUiWidgetCatalogEntry>

export const GEN_UI_WIDGET_CATALOG_ENTRIES = Object.values(
  GEN_UI_WIDGET_CATALOG,
)

export function describeGenUiWidgetCatalog() {
  return GEN_UI_WIDGET_CATALOG_ENTRIES.map(
    ({ type, selectionGuidance }) => `${type}: ${selectionGuidance}`,
  ).join('\n')
}
