import type { FinancialMetricKey } from '@/lib/financial-data/metric-keys'
import type { GenUiWidgetType } from '@/lib/gen-ui/types'

export type CompanySizeBand =
  | 'micro'
  | 'small'
  | 'medium'
  | 'large'
  | 'enterprise'

export type GenUiRecipeTier =
  | 'current'
  | 'aggregate_extension'
  | 'transaction_detail'
  | 'budget_invoice_profitability'

export interface GenUiRecipeRequirements {
  allMetrics?: readonly FinancialMetricKey[]
  anyMetrics?: readonly FinancialMetricKey[]
  historyMetric?: FinancialMetricKey
  forecastMetric?: FinancialMetricKey
  scenarioResult?: boolean
  futureCapabilities?: readonly string[]
}

export interface GenUiWidgetRecipeDefinition {
  number: number
  id: string
  label: string
  description: string
  selectionGuidance: string
  tier: GenUiRecipeTier
  renderer: GenUiWidgetType | null
  requirements: GenUiRecipeRequirements
  audience: readonly CompanySizeBand[]
  redundancyGroup: string
  defaultColumnSpan: 1 | 2
  defaultMetricKeys?: readonly FinancialMetricKey[]
}

const ALL_COMPANY_SIZES: CompanySizeBand[] = [
  'micro',
  'small',
  'medium',
  'large',
  'enterprise',
]

const GROWING_COMPANIES: CompanySizeBand[] = [
  'small',
  'medium',
  'large',
  'enterprise',
]

const COMPLEX_COMPANIES: CompanySizeBand[] = [
  'medium',
  'large',
  'enterprise',
]

export const GEN_UI_WIDGET_RECIPES = [
  {
    number: 1,
    id: 'current_cash_balance',
    label: 'Current cash balance',
    description: 'Shows the latest available cash balance with source provenance.',
    selectionGuidance: 'Use for questions about cash on hand, cash position, or available cash right now.',
    tier: 'current',
    renderer: 'metric_snapshot',
    requirements: { allMetrics: ['cash'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'metric-cash',
    defaultColumnSpan: 1,
    defaultMetricKeys: ['cash'],
  },
  {
    number: 2,
    id: 'cash_runway',
    label: 'Cash runway',
    description: 'Shows estimated months of runway using the latest trusted inputs.',
    selectionGuidance: 'Use for questions about how long cash will last or current runway.',
    tier: 'current',
    renderer: 'metric_snapshot',
    requirements: { allMetrics: ['runway_months'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'metric-runway_months',
    defaultColumnSpan: 1,
    defaultMetricKeys: ['runway_months'],
  },
  {
    number: 3,
    id: 'monthly_burn_rate',
    label: 'Monthly burn rate',
    description: 'Shows current average monthly cash usage and its source.',
    selectionGuidance: 'Use for current burn, spending pace, or monthly cash usage questions.',
    tier: 'current',
    renderer: 'metric_snapshot',
    requirements: { allMetrics: ['burn_rate'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'metric-burn_rate',
    defaultColumnSpan: 1,
    defaultMetricKeys: ['burn_rate'],
  },
  {
    number: 4,
    id: 'runway_date',
    label: 'Runway date',
    description: 'Estimates when cash reaches a selected safety threshold.',
    selectionGuidance: 'Use when the user asks when cash reaches zero or a minimum balance.',
    tier: 'aggregate_extension',
    renderer: null,
    requirements: { allMetrics: ['cash', 'burn_rate'], futureCapabilities: ['cash_threshold_setting'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'runway-timing',
    defaultColumnSpan: 1,
  },
  {
    number: 5,
    id: 'cash_balance_trend',
    label: 'Cash balance trend',
    description: 'Shows historical cash movement from recorded observations.',
    selectionGuidance: 'Use when the user asks how cash changed over time.',
    tier: 'current',
    renderer: 'metric_trend_chart',
    requirements: { historyMetric: 'cash' },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'cash-history',
    defaultColumnSpan: 2,
  },
  {
    number: 6,
    id: 'six_month_cash_forecast',
    label: 'Six-month cash forecast',
    description: 'Projects cash across the next six months from observed movement.',
    selectionGuidance: 'Use for cash forecast questions with a six-month or near-term horizon.',
    tier: 'current',
    renderer: 'metric_forecast_chart',
    requirements: { forecastMetric: 'cash' },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'cash-forecast',
    defaultColumnSpan: 2,
  },
  {
    number: 7,
    id: 'twelve_month_cash_forecast',
    label: 'Twelve-month cash forecast',
    description: 'Projects cash over a longer twelve-month planning horizon.',
    selectionGuidance: 'Use only when the user explicitly requests long-term or twelve-month cash planning.',
    tier: 'aggregate_extension',
    renderer: null,
    requirements: { forecastMetric: 'cash', futureCapabilities: ['twelve_month_metric_forecast'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'cash-forecast',
    defaultColumnSpan: 2,
  },
  {
    number: 8,
    id: 'cash_runway_trend',
    label: 'Cash runway trend',
    description: 'Shows how recorded runway has changed over time.',
    selectionGuidance: 'Use for historical runway movement, deterioration, or improvement questions.',
    tier: 'current',
    renderer: 'metric_trend_chart',
    requirements: { historyMetric: 'runway_months' },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'runway-history',
    defaultColumnSpan: 2,
  },
  {
    number: 9,
    id: 'revenue_forecast',
    label: 'Revenue forecast',
    description: 'Projects future monthly revenue from recorded history.',
    selectionGuidance: 'Use for future revenue, sales, or income questions.',
    tier: 'current',
    renderer: 'metric_forecast_chart',
    requirements: { forecastMetric: 'monthly_revenue' },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'income-forecast',
    defaultColumnSpan: 2,
  },
  {
    number: 10,
    id: 'expense_forecast',
    label: 'Expense forecast',
    description: 'Projects future monthly expenses from recorded history.',
    selectionGuidance: 'Use for future spending, expense, or cost questions.',
    tier: 'current',
    renderer: 'metric_forecast_chart',
    requirements: { forecastMetric: 'monthly_expenses' },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'expense-forecast',
    defaultColumnSpan: 2,
  },
  {
    number: 11,
    id: 'revenue_vs_expenses',
    label: 'Revenue versus expenses',
    description: 'Compares aligned revenue and expense series.',
    selectionGuidance: 'Use when the user asks to compare money coming in with money going out.',
    tier: 'aggregate_extension',
    renderer: null,
    requirements: { allMetrics: ['monthly_revenue', 'monthly_expenses'], futureCapabilities: ['aligned_multi_metric_history'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'operating-performance',
    defaultColumnSpan: 2,
  },
  {
    number: 12,
    id: 'monthly_net_cash_flow',
    label: 'Monthly net cash flow',
    description: 'Shows positive or negative monthly cash movement.',
    selectionGuidance: 'Use for net movement or monthly cash inflow-versus-outflow questions.',
    tier: 'aggregate_extension',
    renderer: null,
    requirements: { allMetrics: ['monthly_revenue', 'monthly_expenses'], futureCapabilities: ['aligned_multi_metric_history'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'operating-performance',
    defaultColumnSpan: 2,
  },
  {
    number: 13,
    id: 'cash_flow_waterfall',
    label: 'Cash flow waterfall',
    description: 'Explains movements from opening to closing cash by component.',
    selectionGuidance: 'Use when the user asks why cash changed or which movements drove the closing balance.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['cash_movement_components'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'cash-movement-explanation',
    defaultColumnSpan: 2,
  },
  {
    number: 14,
    id: 'expense_category_breakdown',
    label: 'Expense category breakdown',
    description: 'Breaks spending into payroll, rent, software, marketing, travel, and other categories.',
    selectionGuidance: 'Use when the user asks which expense categories drive spending.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['categorized_expense_transactions'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'expense-breakdown',
    defaultColumnSpan: 2,
  },
  {
    number: 15,
    id: 'expense_donut',
    label: 'Expense donut chart',
    description: 'Shows the proportional share of spending by category.',
    selectionGuidance: 'Use for a high-level visual answer to where money is being spent.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['categorized_expense_transactions'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'expense-breakdown',
    defaultColumnSpan: 1,
  },
  {
    number: 16,
    id: 'top_expenses',
    label: 'Top expenses',
    description: 'Ranks the largest expense transactions or suppliers.',
    selectionGuidance: 'Use when the user asks for the largest costs or highest spending items.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['expense_transactions'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'expense-ranking',
    defaultColumnSpan: 2,
  },
  {
    number: 17,
    id: 'cost_growth',
    label: 'Cost growth',
    description: 'Ranks categories or suppliers whose costs are increasing fastest.',
    selectionGuidance: 'Use for cost inflation, fast-growing costs, or month-over-month expense questions.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['categorized_expense_history'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'expense-ranking',
    defaultColumnSpan: 2,
  },
  {
    number: 18,
    id: 'unusual_expense_alert',
    label: 'Unusual expense alert',
    description: 'Flags costs significantly above their established baseline.',
    selectionGuidance: 'Use when the user asks about anomalies, unexpected costs, or unusual spending.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['expense_transactions', 'expense_anomaly_baseline'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'expense-alerts',
    defaultColumnSpan: 1,
  },
  {
    number: 19,
    id: 'recurring_expenses',
    label: 'Recurring expenses',
    description: 'Lists detected subscriptions and regular supplier payments.',
    selectionGuidance: 'Use for subscription, recurring payment, or committed-cost questions.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['recurring_expense_detection'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'expense-commitments',
    defaultColumnSpan: 2,
  },
  {
    number: 20,
    id: 'potential_cost_savings',
    label: 'Potential cost savings',
    description: 'Estimates defensible savings from identified discretionary or reducible costs.',
    selectionGuidance: 'Use only when categorized costs provide evidence for a savings estimate.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['categorized_expense_transactions', 'cost_savings_rules'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'cost-optimization',
    defaultColumnSpan: 1,
  },
  {
    number: 21,
    id: 'cost_reduction_simulator',
    label: 'Cost reduction simulator',
    description: 'Lets users reduce real expense categories by selected percentages.',
    selectionGuidance: 'Use for category-specific cost-cutting scenarios when categorized costs are available.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { scenarioResult: true, futureCapabilities: ['categorized_expense_transactions'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'scenario-controls',
    defaultColumnSpan: 2,
  },
  {
    number: 22,
    id: 'burn_rate_simulator',
    label: 'Burn-rate simulator',
    description: 'Models fixed or custom percentage changes to burn using trusted scenario calculations.',
    selectionGuidance: 'Use for questions that increase or decrease monthly burn.',
    tier: 'current',
    renderer: 'scenario_analysis',
    requirements: { scenarioResult: true },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'scenario-analysis',
    defaultColumnSpan: 2,
  },
  {
    number: 23,
    id: 'revenue_change_simulator',
    label: 'Revenue-change simulator',
    description: 'Models revenue growth or decline using trusted scenario calculations.',
    selectionGuidance: 'Use for what-if questions involving a revenue, sales, or income change.',
    tier: 'current',
    renderer: 'scenario_analysis',
    requirements: { scenarioResult: true },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'scenario-analysis',
    defaultColumnSpan: 2,
  },
  {
    number: 24,
    id: 'scenario_comparison_table',
    label: 'Scenario comparison table',
    description: 'Compares baseline and alternative scenario outcomes in a structured table.',
    selectionGuidance: 'Use when exact scenario results need side-by-side numeric comparison.',
    tier: 'current',
    renderer: 'scenario_analysis',
    requirements: { scenarioResult: true },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'scenario-analysis',
    defaultColumnSpan: 2,
  },
  {
    number: 25,
    id: 'scenario_comparison_chart',
    label: 'Scenario comparison chart',
    description: 'Shows baseline and alternative forecast paths together.',
    selectionGuidance: 'Use when the shape and timing of scenario outcomes matter.',
    tier: 'current',
    renderer: 'scenario_analysis',
    requirements: { scenarioResult: true },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'scenario-analysis',
    defaultColumnSpan: 2,
  },
  {
    number: 26,
    id: 'editable_assumptions',
    label: 'Editable assumptions',
    description: 'Provides controls for scenario revenue, payroll, expenses, timing, and other explicit assumptions.',
    selectionGuidance: 'Use when the user wants to refine or rerun a calculated scenario.',
    tier: 'current',
    renderer: 'scenario_analysis',
    requirements: { scenarioResult: true },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'scenario-analysis',
    defaultColumnSpan: 2,
  },
  {
    number: 27,
    id: 'assumptions_summary',
    label: 'Assumptions summary',
    description: 'Lists the exact assumptions supporting a forecast or scenario.',
    selectionGuidance: 'Use when transparency about scenario assumptions adds decision value.',
    tier: 'current',
    renderer: 'scenario_analysis',
    requirements: { scenarioResult: true },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'scenario-analysis',
    defaultColumnSpan: 2,
  },
  {
    number: 28,
    id: 'forecast_confidence',
    label: 'Forecast confidence',
    description: 'Explains forecast reliability from observation count, provenance, and source confidence.',
    selectionGuidance: 'Use when the user asks how reliable, complete, or trustworthy a forecast is.',
    tier: 'current',
    renderer: 'metric_source_evidence',
    requirements: { anyMetrics: ['cash', 'monthly_revenue', 'monthly_expenses', 'burn_rate', 'runway_months'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'forecast-evidence',
    defaultColumnSpan: 2,
  },
  {
    number: 29,
    id: 'forecast_range',
    label: 'Forecast range',
    description: 'Shows expected, optimistic, and pessimistic paths from explicit scenario assumptions.',
    selectionGuidance: 'Use when a trusted scenario result contains multiple comparable outcomes.',
    tier: 'current',
    renderer: 'scenario_analysis',
    requirements: { scenarioResult: true },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'scenario-analysis',
    defaultColumnSpan: 2,
  },
  {
    number: 30,
    id: 'budget_vs_actual',
    label: 'Budget versus actual',
    description: 'Compares actual financial performance with an approved budget.',
    selectionGuidance: 'Use for budget performance and plan-versus-actual questions.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['budget_lines', 'actual_accounting_lines'] },
    audience: COMPLEX_COMPANIES,
    redundancyGroup: 'budget-performance',
    defaultColumnSpan: 2,
  },
  {
    number: 31,
    id: 'budget_variance_table',
    label: 'Budget variance table',
    description: 'Shows dollar and percentage budget variances by line or category.',
    selectionGuidance: 'Use when the user needs detailed variance amounts rather than only a chart.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['budget_lines', 'actual_accounting_lines'] },
    audience: COMPLEX_COMPANIES,
    redundancyGroup: 'budget-performance',
    defaultColumnSpan: 2,
  },
  {
    number: 32,
    id: 'revenue_variance',
    label: 'Revenue variance',
    description: 'Shows revenue above or below budget or forecast.',
    selectionGuidance: 'Use for focused revenue variance questions.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['revenue_budget_actual'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'budget-variance-metrics',
    defaultColumnSpan: 1,
  },
  {
    number: 33,
    id: 'expense_variance',
    label: 'Expense variance',
    description: 'Shows spending above or below budget or forecast.',
    selectionGuidance: 'Use for focused expense variance questions.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['expense_budget_actual'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'budget-variance-metrics',
    defaultColumnSpan: 1,
  },
  {
    number: 34,
    id: 'accounts_receivable_summary',
    label: 'Accounts receivable summary',
    description: 'Shows the latest total amount customers owe.',
    selectionGuidance: 'Use for current receivables or money-owed questions that do not require invoice detail.',
    tier: 'current',
    renderer: 'metric_snapshot',
    requirements: { allMetrics: ['accounts_receivable'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'metric-accounts_receivable',
    defaultColumnSpan: 1,
    defaultMetricKeys: ['accounts_receivable'],
  },
  {
    number: 35,
    id: 'overdue_invoices',
    label: 'Overdue invoices',
    description: 'Shows customer, amount, invoice date, due date, and days overdue.',
    selectionGuidance: 'Use for collections, overdue customers, or unpaid invoice questions.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['sales_invoices'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'receivables-detail',
    defaultColumnSpan: 2,
  },
  {
    number: 36,
    id: 'receivables_ageing',
    label: 'Accounts receivable ageing',
    description: 'Groups receivables into 0–30, 31–60, 61–90, and 90+ day buckets.',
    selectionGuidance: 'Use when the age and collection risk of receivables matters.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['sales_invoices'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'receivables-detail',
    defaultColumnSpan: 2,
  },
  {
    number: 37,
    id: 'accounts_payable_summary',
    label: 'Accounts payable summary',
    description: 'Shows the latest total amount owed to suppliers.',
    selectionGuidance: 'Use for current payables or supplier-money-owed questions without bill detail.',
    tier: 'current',
    renderer: 'metric_snapshot',
    requirements: { allMetrics: ['accounts_payable'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'metric-accounts_payable',
    defaultColumnSpan: 1,
    defaultMetricKeys: ['accounts_payable'],
  },
  {
    number: 38,
    id: 'upcoming_bills_timeline',
    label: 'Upcoming bills timeline',
    description: 'Shows supplier payments due over upcoming days and months.',
    selectionGuidance: 'Use when the timing of upcoming bills affects cash planning.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['supplier_bills'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'payment-timing',
    defaultColumnSpan: 2,
  },
  {
    number: 39,
    id: 'large_upcoming_payments',
    label: 'Large upcoming payments',
    description: 'Flags major scheduled supplier or other cash outflows.',
    selectionGuidance: 'Use when the user asks about major near-term cash commitments.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['supplier_bills', 'payment_size_baseline'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'payment-alerts',
    defaultColumnSpan: 1,
  },
  {
    number: 40,
    id: 'expected_customer_payments',
    label: 'Expected customer payments',
    description: 'Shows when outstanding customer payments are expected to arrive.',
    selectionGuidance: 'Use for expected collections and incoming-cash timing questions.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['sales_invoices'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'payment-timing',
    defaultColumnSpan: 2,
  },
  {
    number: 41,
    id: 'cash_shortage_warning',
    label: 'Cash shortage warning',
    description: 'Warns when current runway or projected cash indicates dangerous liquidity.',
    selectionGuidance: 'Use for liquidity risk, cash shortage, or cash-out timing questions.',
    tier: 'current',
    renderer: 'risk_threshold_timeline',
    requirements: { allMetrics: ['runway_months'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'liquidity-alerts',
    defaultColumnSpan: 1,
  },
  {
    number: 42,
    id: 'minimum_cash_threshold',
    label: 'Minimum cash threshold',
    description: 'Compares cash with a company-defined minimum safe balance.',
    selectionGuidance: 'Use when the user asks about their safety buffer or minimum balance policy.',
    tier: 'aggregate_extension',
    renderer: null,
    requirements: { allMetrics: ['cash'], futureCapabilities: ['cash_threshold_setting'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'liquidity-alerts',
    defaultColumnSpan: 1,
  },
  {
    number: 43,
    id: 'three_month_runway_marker',
    label: 'Three-month runway marker',
    description: 'Shows whether runway is above or below the urgent three-month threshold.',
    selectionGuidance: 'Use when the user asks about a three-month runway threshold or urgent liquidity risk.',
    tier: 'current',
    renderer: 'risk_threshold_timeline',
    requirements: { allMetrics: ['runway_months'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'liquidity-alerts',
    defaultColumnSpan: 1,
  },
  {
    number: 44,
    id: 'break_even_calculation',
    label: 'Break-even calculation',
    description: 'Calculates revenue required to cover fixed and variable costs.',
    selectionGuidance: 'Use only when cost structure and gross-margin inputs support a true break-even calculation.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['fixed_variable_costs', 'gross_margin'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'break-even',
    defaultColumnSpan: 1,
  },
  {
    number: 45,
    id: 'break_even_timeline',
    label: 'Break-even timeline',
    description: 'Estimates when forecast revenue covers forecast costs.',
    selectionGuidance: 'Use when the user asks when the business is expected to break even.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['fixed_variable_costs', 'gross_margin', 'profit_forecast'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'break-even',
    defaultColumnSpan: 2,
  },
  {
    number: 46,
    id: 'profitability_summary',
    label: 'Profitability summary',
    description: 'Shows revenue, gross profit, operating profit, and net profit.',
    selectionGuidance: 'Use for a trusted profitability overview backed by detailed profit-and-loss data.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['detailed_profit_and_loss'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'profitability',
    defaultColumnSpan: 2,
  },
  {
    number: 47,
    id: 'gross_margin_trend',
    label: 'Gross margin trend',
    description: 'Shows whether gross margin is improving or declining.',
    selectionGuidance: 'Use for margin movement questions backed by revenue and cost-of-sales history.',
    tier: 'budget_invoice_profitability',
    renderer: null,
    requirements: { futureCapabilities: ['gross_margin_history'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'profitability',
    defaultColumnSpan: 2,
  },
  {
    number: 48,
    id: 'customer_concentration',
    label: 'Customer concentration',
    description: 'Shows how much revenue depends on major customers.',
    selectionGuidance: 'Use for customer dependency, concentration, or revenue-risk questions.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['customer_revenue_detail'] },
    audience: GROWING_COMPANIES,
    redundancyGroup: 'concentration-risk',
    defaultColumnSpan: 2,
  },
  {
    number: 49,
    id: 'supplier_concentration',
    label: 'Supplier concentration',
    description: 'Shows how much spending depends on major suppliers.',
    selectionGuidance: 'Use for supplier dependency, concentration, or continuity-risk questions.',
    tier: 'transaction_detail',
    renderer: null,
    requirements: { futureCapabilities: ['supplier_expense_detail'] },
    audience: COMPLEX_COMPANIES,
    redundancyGroup: 'concentration-risk',
    defaultColumnSpan: 2,
  },
  {
    number: 50,
    id: 'recommended_actions',
    label: 'Recommended actions',
    description: 'Ranks evidence-based financial actions from the available metrics and risks.',
    selectionGuidance: 'Use when the user asks what to do next, how to respond, or which actions deserve priority.',
    tier: 'current',
    renderer: 'planning_checklist',
    requirements: { anyMetrics: ['cash', 'burn_rate', 'runway_months', 'accounts_receivable', 'accounts_payable'] },
    audience: ALL_COMPANY_SIZES,
    redundancyGroup: 'recommended-actions',
    defaultColumnSpan: 1,
  },
] as const satisfies readonly GenUiWidgetRecipeDefinition[]

type GenUiWidgetRecipeLiteral = (typeof GEN_UI_WIDGET_RECIPES)[number]
export type GenUiWidgetRecipeId = GenUiWidgetRecipeLiteral['id']
export type GenUiWidgetRecipe = GenUiWidgetRecipeDefinition & {
  id: GenUiWidgetRecipeId
}

export const GEN_UI_WIDGET_RECIPE_BY_ID = Object.fromEntries(
  GEN_UI_WIDGET_RECIPES.map((recipe) => [recipe.id, recipe])
) as unknown as Record<GenUiWidgetRecipeId, GenUiWidgetRecipe>

export function describeGenUiWidgetRecipes(recipes: readonly GenUiWidgetRecipe[]) {
  return recipes.map((recipe) => ({
    id: recipe.id,
    label: recipe.label,
    description: recipe.description,
    selectionGuidance: recipe.selectionGuidance,
    audience: recipe.audience,
  }))
}
